apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  # Fixed selector to match the actual pod labels
  # The pods have labels: app=webapp, tier=frontend
  # This service now correctly looks for: app=webapp
  selector:
    app: webapp
  type: ClusterIP